### PR TITLE
[5.10] Cherry-pick multiple PRs to `release/5.10`

### PR DESCRIPTION
**Pull request by ahoppen**
* **Explanation**: Cherry-picks the following PRs to `release/5.10`
  * [Throw an error if types conforming to MemberMacro implement no expansion method](https://github.com/apple/swift-syntax/pull/2319)
  * [Move swift-parser-cli to its own package](https://github.com/apple/swift-syntax/pull/2063)
  * [Fix missing space in LabeledExprSyntax init](https://github.com/apple/swift-syntax/pull/2291)
  * [Update the interpolation failure message](https://github.com/apple/swift-syntax/pull/2290)
  * [Rename NoteMessage.fixItID to noteID](https://github.com/apple/swift-syntax/pull/2264)
  * [Mark SyntaxChildrenIndex as Sendable](https://github.com/apple/swift-syntax/pull/2322)
  * [Conform MessageID and DiagnosticSeverity to Sendable](https://github.com/apple/swift-syntax/pull/1822)
  * [Optimized Type Checker performance in UnicodeScalarExtensions and SyntaxText](https://github.com/apple/swift-syntax/pull/2308)
* **Risk**: Low
* **Testing**: New test cases added by the PRs
* **Issue**: rdar://116485448
* **Reviewer**:  Multiple, mostly @ahoppen

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69963

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69963

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/69963

@swift-ci Please test Windows

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/69963

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
