### PR TITLE
Include property names in debug description

### PR DESCRIPTION
**Pull request by ahoppen**
This adds child the name of child properties in the debug description inside parenthesis. E.g. for the following source code

```swift
switch foo {
  case 1:
    return "one"
}
```

we print the following:

```
SourceFileSyntax
├─CodeBlockItemListSyntax (statements)
│ ╰─CodeBlockItemSyntax
│   ╰─EnumDeclSyntax (item)
│     ├─keyword(SwiftSyntax.Keyword.enum) (enumKeyword)
│     ├─identifier("Foo") (identifier)
│     ╰─MemberDeclBlockSyntax (members)
│       ├─leftBrace (leftBrace)
│       ├─MemberDeclListSyntax (members)
│       │ ├─MemberDeclListItemSyntax
│       │ │ ╰─EnumCaseDeclSyntax (decl)
│       │ │   ├─keyword(SwiftSyntax.Keyword.case) (caseKeyword)
│       │ │   ╰─EnumCaseElementListSyntax (elements)
│       │ │     ╰─EnumCaseElementSyntax
│       │ │       ╰─identifier("first") (identifier)
│       │ ╰─MemberDeclListItemSyntax
│       │   ╰─EnumCaseDeclSyntax (decl)
│       │     ├─keyword(SwiftSyntax.Keyword.case) (caseKeyword)
│       │     ╰─EnumCaseElementListSyntax (elements)
│       │       ╰─EnumCaseElementSyntax
│       │         ╰─identifier("second") (identifier)
│       ╰─rightBrace (rightBrace)
╰─eof (eofToken)

```

---

I also considered adding the child name in front of the type but found the notation using parentheses more readable. If the consensus is that the prefix notation with `:` is better, I’m happy to change it.

```
SourceFileSyntax
├─statements: CodeBlockItemListSyntax
│ ╰─CodeBlockItemSyntax
│   ╰─item: EnumDeclSyntax
│     ├─enumKeyword: keyword(SwiftSyntax.Keyword.enum)
│     ├─identifier: identifier("Foo")
│     ╰─members: MemberDeclBlockSyntax
│       ├─leftBrace: leftBrace
│       ├─members: MemberDeclListSyntax
│       │ ├─MemberDeclListItemSyntax
│       │ │ ╰─decl: EnumCaseDeclSyntax
│       │ │   ├─caseKeyword: keyword(SwiftSyntax.Keyword.case)
│       │ │   ╰─elements: EnumCaseElementListSyntax
│       │ │     ╰─EnumCaseElementSyntax
│       │ │       ╰─identifier: identifier("first")
│       │ ╰─MemberDeclListItemSyntax
│       │   ╰─decl: EnumCaseDeclSyntax
│       │     ├─caseKeyword: keyword(SwiftSyntax.Keyword.case)
│       │     ╰─elements: EnumCaseElementListSyntax
│       │       ╰─EnumCaseElementSyntax
│       │         ╰─identifier: identifier("second")
│       ╰─rightBrace: rightBrace
╰─eofToken: eof

```

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by kimdv — APPROVED** [review]
🥳

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by rintaro** [comment]
I prefer prefix child name.
When you want to access some descendant from a given node, I feel it is more readable:
```
SourceFileSyntax
├─statements: CodeBlockItemListSyntax
│ ╰─[0]: CodeBlockItemSyntax
│   ╰─item: EnumDeclSyntax
│     ├─enumKeyword: keyword(SwiftSyntax.Keyword.enum)
│     ├─identifier: identifier("Foo")
│     ╰─memberBlock: MemberDeclBlockSyntax
│       ├─leftBrace: leftBrace
...
```
You can easily write `node.statements[0].item.memberBlock` without moving your sight to the end of lines.

(Yes I'd like `[n]: ` in collections)

**Comment by bnbarham** [comment]
I like the `[n]` idea. I don't have a strong preference for before/after. The `:` syntax has the advantage that `()` is already used so it seems less busy to me. But it's debugging text so I'd get used to either.

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by ahoppen** [comment]
Thanks for the feedback. I updated the PR to include the child name as a prefix and use `[0]` etc for collections.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
