### PR TITLE
Resolve `switch covers known cases, but 'Enum' may have additional unknown values` warnings

### PR DESCRIPTION
**Pull request by tshortli**
When building with CMake during the Swift compiler build, the libraries in this package are built with library evolution enabled. That causes the compiler to emit diagnostics that encourage use of `@unknown default` to handle unknown cases that might be added in the future. Silence these warnings by adding `@unknown default` cases where they are missing. Guard these with the `RESILIENT_LIBRARIES` compilation condition to avoid triggering a `Default will never be executed` diagnostic during the package build.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

**Comment by tshortli** [comment]
@swift-ci please smoke test

**Review by ahoppen — APPROVED** [review]
Thanks!

**Comment by tshortli** [comment]
@swift-ci please test macOS

**Comment by tshortli** [comment]
@swift-ci please test Windows

**Pull request merged**
