### PR TITLE
Update year in header

### PR DESCRIPTION
**Pull request by kimdv**
Not sure if this is needed. But I saw some was some years behind.

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci Please test

**Review by ahoppen — COMMENTED** [review]
Yes, we never really maintain those. But updating the dates does seem like a good idea.

[c-syntax-nodes.h](https://github.com/apple/swift-syntax/blob/main/Sources/_CSwiftSyntax/include/c-syntax-nodes.h) needs to match [SwiftSyntaxCDataTypes.h](https://github.com/apple/swift/blob/main/include/swift-c/SyntaxParser/SwiftSyntaxCDataTypes.h) in the main Swift repo. I’ll leave it up to you to either update the date in that repo as well or leave the copy right of that file in this repo as-is.

**Comment by kimdv** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
> [c-syntax-nodes.h](https://github.com/apple/swift-syntax/blob/main/Sources/_CSwiftSyntax/include/c-syntax-nodes.h) needs to match [SwiftSyntaxCDataTypes.h](https://github.com/apple/swift/blob/main/include/swift-c/SyntaxParser/SwiftSyntaxCDataTypes.h) in the main Swift repo. I’ll leave it up to you to either update the date in that repo as well or leave the copy right of that file in this repo as-is.

Updated in https://github.com/apple/swift/pull/41453

**Comment by kimdv** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/41453

@swift-ci Please test

**Pull request merged**
