### PR TITLE
Split token and layout specific methods to specific views

### PR DESCRIPTION
**Pull request by ahoppen**
This should make it obvious when you are accessing properties that only exist on tokens or views.

Also shuffled the API a little bit (e.g. removing children accessors that weren’t providing real value).

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60635

@swift-ci Please test

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60635

@swift-ci Please test

**Pull request merged**
