### PR TITLE
Add missing code for parser entry template and fix `build-script.py`

### PR DESCRIPTION
**Pull request by kimdv**
In #1346 code was modified on the file and not in the template

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
The error was properly introduced in #1149 where we refactored the code-gen into a single executable. 

Not sure why the CI didn't catch that before

**Comment by kimdv** [comment]
@swift-ci plese test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by keith** [comment]
@kimdv looks like things don't build without this, is it good to merge?

**Comment by kimdv** [comment]
> @kimdv looks like things don't build without this, is it good to merge?

For me yea. But we need approval from @ahoppen I think 🤔

**Comment by keith** [comment]
@swift-ci please test and merge

**Comment by keith** [comment]
Let's merge and do post-commit review if needed to unblock folks

**Comment by gottesmm** [comment]
@Keith this broke the build: https://ci.swift.org/job/oss-swift-incremental-RA-macos/2331/. I am going to try reverting it.

**Comment by keith** [comment]
dang, sorry, thanks! looks like we need to run the integration tests before merging again

**Comment by ahoppen** [comment]
> Not sure why the CI didn't catch that before

We don’t verify that the CodeGenerated files match the templates because running code generation requires us to check out an older version of SwiftSyntax (the one specified in the Package.swift of CodeGeneration). But CI doesn’t have internet access at that point to perform that checkout… So it’s a little tricky to do.

**Pull request merged**
