### PR TITLE
[5.5] Degyb for nullable PostfixIfConfigExpr.base

### PR DESCRIPTION
**Pull request by rintaro**
Update for apple/swift#38418

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/38418
@swift-ci Please test

**Review by akyrtzi — APPROVED** [review]

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/38418
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/38418
@swift-ci Please test

**Pull request merged**
