### PR TITLE
Add leading and trailing spacing for `SpacedBinaryOperator`

### PR DESCRIPTION
**Pull request by kimdv**
Swift PR: https://github.com/apple/swift/pull/40030

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/40030

@swift-ci Please test

**Comment by kimdv** [comment]
Will rebase when #332 is merged. 
Then we can trigger it again. 😁

**Comment by kimdv** [comment]
@ahoppen rebased! 🚀

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/40030

@swift-ci Please test

**Pull request merged**
