### PR TITLE
MultiLineStringLiteralDiagnoticsGenerator -> MultiLineStringLiteralDiagnosticsGenerator

### PR DESCRIPTION
**Pull request by sophiapoirier**

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Review by kimdv — APPROVED** [review]
Thanks @sophiapoirier 😁

**Comment by sophiapoirier** [comment]
@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
@swift-ci please test Windows

**Pull request merged**
