### PR TITLE
Cherry-pick multiple PRs to `release/5.9`

### PR DESCRIPTION
**Pull request by ahoppen**
Cherry-picks the following PRs to `release/5.9`:

- #1490
  - Documentation-only change, risk 0/5
- #1497
  - Fixes a warning in tests, risk 0/5
- #1514
  - TODO: REMOVE
- #1482
  - Improvements to SwiftSyntax’s public API that we want to ship in 509, risk 3/5
- #1519
  - Just fixes a compilation warning, risk 1/5
- #1520
  - Fixes escaping of #️⃣ in string literals, risk 1/5
- #1454
  - Changes the syntax nodes and I would thus like to include it in 509, risk 2/5
- #1518
  - Improves formatting in BasicFormat, risk 1/5
- #1527
  - Documentation-only change, risk 0/5
- #1517
  - Fixes a major bug in `SwiftSyntaxBuilder` where paramters had incorrect default values, risk 2/5
- #1466
  - Increases test coverage in CI only, risk 1/5
- #1503, #1539
  - Drastically improves the debug output of syntax nodes, risk 1/5
- #1523
  - Improves documentation only, risk 0/5
- #1526
  - Adds more assertions to make debug and release builds behave more similar, risk 2/5
- #1524
  - Performs an API rename that I really want to get in before people are using SwiftSyntax for macros, risk 1/5
- #1538
  - Fixes two minor misparses, risk 1/5
- #1541
  - Just moving code around, will make cherry-picking a lot easier, risk 1/5
- #1340
  - Adds a new testing technique to the parser behind a conditional compilation flag that is only present in CI, risk 1/5
- #1544
  - Removes a deprecated module that we don't want to ship with SwiftSyntax 509

### CODE REVIEW

**Review by DougGregor — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test macOS

**Review by DougGregor — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test macOS

**Review by DougGregor — APPROVED** [review]

**Comment by ahoppen** [comment]
apple/swift#65239
apple/swift-stress-tester#235
apple/swift-format#514

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test linux

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/65239
https://github.com/apple/swift-stress-tester/pull/235
https://github.com/apple/swift-format/pull/514

@swift-ci Please test windows

**Comment by jpsim** [comment]
When you get a chance could you please tag a new `509.0.0-swift-5.9-DEVELOPMENT-SNAPSHOT-2023-04-...` development snapshot tag with these changes so we can use them in SwiftLint?

Thanks!

**Pull request merged**
