### PR TITLE
Build with downloaded snapshot

### PR DESCRIPTION
**Pull request by krzyzanowskim**
Instead of building with swift sources, it is possible to build a `swift-syntax` binary with a downloaded snapshot from swift.org

To do so, this PR adds `gyb` and `lit` dependencies from swift and llvm repositories. Now it's enough to specify a toolchain swiftc path to build libSwiftSyntax

```
$ ./build-script.py --swiftc-exec ../swift-snapshot/usr/bin/swiftc
```

Tests needs `FileCheck` that is not included in the repo and the path have to specify by hand, eg.:

```
$ ./build-script.py -t --swiftc-exec ../swift-snapshot/usr/bin/swiftc --filecheck-exec ../build/Ninja-RelWithDebInfoAssert/llvm-macosx-x86_64/bin/FileCheck
```

The new behavior is optional and build script fallback to `../swift` paths if exists - current behavior.

### CODE REVIEW

**Comment by ahoppen** [comment]
While it's great that we can build swiftSyntax without building swift, I don't think that copying the `lit`, `gyb` and `gyb_syntax_support` sources is the right approach.

Copying `lit` and `gyb` from the llvm / swift repo means that its development will most certainly diverge from their original repository, which is definitely not desirable since the tools should be the same.

The version of `gyb_syntax_support` used by the compiler and and the one used by SwiftSyntax need to be the same, so they have a common understanding on how the syntax tree is structured. Allowing them to diverge will be a subtle source of hard-to-track-down bugs.

**Comment by krzyzanowskim** [comment]
`lit` is totaly optional here and could be just removed - I guess it's better to be able to build libSwiftSyntax with a snapshot, than run tests with it.

> The version of gyb_syntax_support used by the compiler and and the one used by SwiftSyntax need to be the same, so they have a common understanding on how the syntax tree is structured. Allowing them to diverge will be a subtle source of hard-to-track-down bugs.

What's the better approach you think about? the `gyb_syntax_support` being part of `swift` repository is a bit  annoying. Building swift source as a dependency is a pain. Clone swift and llvm to get the those dependencies is eh.

swift-syntax [claim](https://github.com/apple/swift-syntax#usage) to tag releases with tags. `gyb` dependency could be cloned by the build script directly from the swift repo maybe.

**Comment by allevato** [comment]
You don't actually have to _build_ the Swift sources to build swift-syntax, right? I thought they just needed to be checked out side-by-side so that the build script could reach all the syntax support files, but you can build it with whenever toolchain you have (that's compatible with those Swift sources).

That's what the [contribution guidelines](https://github.com/apple/swift-syntax#contributing) imply, at least.

**Comment by ahoppen** [comment]
I know it's not ideal that `swift` and `llvm` need to be cloned but since SwiftSyntax does, in fact, depend on sources that need to be shared with the compiler repository (`gyb_syntax_support`) I can't think of a way to remove a dependency that does exist. 

To resolve the dependency in practice (and to work around the issue that SwiftPM can't invoke `lit`) we decided to generate all gyb files under the tag. What tags do you think are missing? Or would you like to contribute to SwiftSyntax and thus require a `master` build?

**Comment by krzyzanowskim** [comment]
So... there is no actual verification if a checkout `swift` is in sync with `swift-syntax`, is it? That still may be the source of hard-to-track-down bugs. I mean, my cloned `swift` may be at any stage - as long as it builds. The `build-script.py` and `update-toolchain.py` just use whatever is there and try to use it.

That said. I should be able to clone `swift-syntax`, tagged `swift-DEVELOPMENT-SNAPSHOT-2019-01-12-a` and build with with downloaded [swift-DEVELOPMENT-SNAPSHOT-2019-01-15-a-osx.pkg](https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2019-01-15-a/swift-DEVELOPMENT-SNAPSHOT-2019-01-15-a-osx.pkg) toolchain - without cloning the `swift` and `llvm`, right? it can't be easily done currenlty.

`build-script.py` could copy over dependency (it's not obvious what commit should be fetched for `master` branch - probably master-master). Normally, submodules keep that kind of dependency (or tree or whatever).

I guess, this should be enough to bring the current gyb to the repo, wdyt?
```
curl -L https://github.com/apple/swift/tarball/master | tar -xzv --strip-components 2 --include=*utils/gyb*
```

> What tags do you think are missing? Or would you like to contribute to SwiftSyntax and thus require a master build?

I want to use a version that is not a swift5, due to libSyntax.

**Comment by nkcsgexi** [comment]
As @ahoppen and @allevato said, SwiftSyntax has to depend on some source files from the Swift repo to build. That's why we need to clone Swift repo along with SwiftSyntax. It's also a good point that we don't have a way to build SwiftSyntax with an existing toolchain as mentioned by @krzyzanowskim . 

With that said, i don't like this idea of duplicating these files among two repository. This practice will double maintenance costs. We should explore other options.

How about we install these gyb support files (DeclNodes.py, etc) to an OSS toolchain so that users can build their SwiftSyntax in sync with the compiler, just like we install headers.

CC: @akyrtzi @harlanhaskins and @rintaro

**Comment by akyrtzi** [comment]
To clarify some things:

> Building swift source as a dependency is a pain.

It was our intention that every time a new snapshot of swift toolchain is released that an associated tag is created on swift-syntax repo that includes the gyb-generated files. Then in order to build swift-syntax as a dependency, without needing swift repo checked out, you'd depend on the right branch or tag.
This seems to have fallen out of our radar, we'll look into configuring the bots properly for this.

> So... there is no actual verification if a checkout swift is in sync with swift-syntax, is it?

This is true but we are going to correct this. Now that swift-syntax depends on the new parser library for syntax tree creation what we are going to do is that gyb_syntax_support will form a string or a hash that identifies the unique configuration of syntax nodes structure, and this string will be compiled in both the parser library on the swift repo side and swift-syntax. At runtime when you invoke `SyntaxParser` it will perform a check that the parser library it loaded with is in-sync with the expected configuration of syntax nodes, and if it is not it will throw an error.

That means that if you run swift-syntax against a mismatched swift parser library it will fail immediately.

Overall we'd much prefer to keep gyb_syntax_support in one place only, not have copies in both swift and swift-syntax repositories. Whether we should be committing the gyb-generated files or not directly in master of swift-syntax is debatable but once we set up automatic tagging with the generated files included it shouldn't be so important.

**Comment by akyrtzi** [comment]
It's not useful to keep a PR open that we are not going to accept, a JIRA is more appropriate to keep track of tasks.

**Comment by krzyzanowskim** [comment]
https://bugs.swift.org/browse/SR-9798

**Pull request closed without merging**
