### PR TITLE
[5.6] rewrite swiftSettings to avoid causing SPM build failures

### PR DESCRIPTION
**Pull request by keith**
Cherry picked from https://github.com/apple/swift-syntax/pull/358

Fixes https://bugs.swift.org/browse/SR-15989

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
Thanks for the fix. We are currently investigating the best procedure to create a hot fix release for SwiftSyntax with this change. I hope to have an answer and be able to create a `0.50600.1` release of SwiftSyntax in the next couple of days.

**Review by airspeedswift — APPROVED** [review]
Approving this for 5.6 because even though that release has shipped, this fixes compatibility when building from source.

**Comment by ahoppen** [comment]
Thanks a lot for noticing the issue and providing this PR so quickly after the 0.50600.0 release of SwiftSyntax. I have just published a 0.50600.1 release that includes this patch.

**Pull request merged**
