### PR TITLE
Renamed generate-swiftsyntax to generate-swift-syntax

### PR DESCRIPTION
**Pull request by arirays**
Fixing issue #1935

### CODE REVIEW

**Comment by kimdv** [comment]
@arirays I think a rebase is needed. 
Would you mind to do that 😁

**Comment by ahoppen** [comment]
@arirays I took the liberty to add a commit to your branch that should resolve the failures from the rebase.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
