### PR TITLE
Don't treat a `#` as starting a declaration.

### PR DESCRIPTION
**Pull request by DougGregor**
The recent change to rely on the general macro-expansion expression nodes for `#line` et al broke return statements because we were classifying the expression as a declaration.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
Some lookahead-related tests flipped polarity here

```
Test Case '-[SwiftParserTest.RawStringErrorsTests testRawStringErrors3]' failed (0.007 seconds).
Test Case '-[SwiftParserTest.RawStringErrorsTests testRawStringErrors4]' started.
Test Case '-[SwiftParserTest.RawStringErrorsTests testRawStringErrors4]' passed (0.000 seconds).
Test Case '-[SwiftParserTest.RawStringErrorsTests testRawStringErrors5]' started.
/Users/ec2-user/jenkins/workspace/swift-syntax-PR-macOS/branch-main/swift-syntax/Tests/SwiftParserTest/translated/RawStringErrorsTests.swift:73: error: -[SwiftParserTest.RawStringErrorsTests testRawStringErrors5] : failed - Actual output (+) differed from expected output (-):
–expected identifier in pound literal declaration
+expected identifier in pound literal expression
/Users/ec2-user/jenkins/workspace/swift-syntax-PR-macOS/branch-main/swift-syntax/Tests/SwiftParserTest/translated/RawStringErrorsTests.swift:74: error: -[SwiftParserTest.RawStringErrorsTests testRawStringErrors5] : failed - Actual output (+) differed from expected output (-):
–expected identifier in pound literal declaration
+expected identifier in pound literal expression
/Users/ec2-user/jenkins/workspace/swift-syntax-PR-macOS/branch-main/swift-syntax/Tests/SwiftParserTest/translated/RawStringErrorsTests.swift:75: error: -[SwiftParserTest.RawStringErrorsTests testRawStringErrors5] : failed - Actual output (+) differed from expected output (-):
–expected identifier in pound literal declaration
+expected identifier in pound literal expression
```

**Comment by DougGregor** [comment]
> Some lookahead-related tests flipped polarity here

This is a Good Thing, because it's actually valuable for these to be expressions in these contexts, but it's a Bad Thing that I missed these and have to restart PR testing.

**Comment by DougGregor** [comment]
@swift-ci please test

**Pull request merged**
