### PR TITLE
Handle unexpected token before in keyword in for statements

### LINKED ISSUE #2406: Too much skipping after invalid token in `for` element name
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
for var elem? in arr { }
```

### Description

This results diagnostics:
```
test.swift:1:13: error: expected 'in' and expression in 'for' statement
1 │ for var elem? in arr { }
  │             ├─ error: expected 'in' and expression in 'for' statement
  │             ╰─ error: unexpected code '? in arr' in 'for' statement
2 │ 
```
And in the parsed syntax tree `? in arr ` part is parsed as `CodeBlockItemSyntax.unexpectedBeforeLeftBrace`

### PR DESCRIPTION
**Pull request by kimdv**
Fixed #2406

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Thanks 👍🏽

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci Please test windows

**Pull request merged**
