### PR TITLE
build-script: pass '-enforce-exclusivity=unchecked' to speed-up compilation

### PR DESCRIPTION
**Pull request by nkcsgexi**
rdar://47101451

### CODE REVIEW

**Comment by nkcsgexi** [comment]
@swift-ci please smoke test

**Comment by keith** [comment]
Out of curiosity how significant is the different you see with this flag? On our codebase it appears to be a no-op vs the default

**Comment by nkcsgexi** [comment]
The significance may vary according to build settings. We experimented with our internal setting and such change does make a significant difference.

**Comment by akyrtzi** [comment]
It will vary by codebase, if you don't see significant difference then there's no need to pass the flag.

**Comment by keith** [comment]
Yea we definitely didn't add it, I was just curious what percent this was helping for this codebase

**Comment by akyrtzi** [comment]
it's multiples, slower 7x ~ 12x, depending on what version of swift compiler was used.

**Pull request merged**
