### PR TITLE
Allow putting garbage nodes in between any two children of a Syntax node

### PR DESCRIPTION
**Pull request by ahoppen**
Companion of https://github.com/apple/swift/pull/60211

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60211

@swift-ci Please test

**Comment by CodaFi** [comment]
I presume we'll come around and clean up the places we're allowing you to stick garbage explicitly in the tree then? 
- CodeBlockItemSyntax
- AttributeSyntax

**Review by CodaFi — APPROVED** [review]

**Comment by ahoppen** [comment]
Yes, I wanted to do that in a follow-up PR to keep this one focused.

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60211

@swift-ci Please test

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60211

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60211

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60211

@swift-ci Please test

**Pull request merged**
