### PR TITLE
Generate with syntax kind bug fix

### PR DESCRIPTION
**Pull request by kimdv**
@ahoppen 

I changed to `endswith("token")`and it seemed to generate correct (of what I understand).

https://github.com/apple/swift/pull/37382

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/37382

@swift-ci Please test

**Review by ahoppen — APPROVED** [review]
Nice! Looks good.

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Comment by ahoppen** [comment]
apple/swift#37382

@swift-ci Please test Linux

**Comment by kimdv** [comment]
@ahoppen it says `16:14:44 FAIL: Gyb-generated files committed to repository do not match generated ones. Please re-generate the gyb-files and recommit them.`

But if I regenerate locally it don't change anything? 

Should I rebase apple/swift#37382 to latest master?

**Comment by ahoppen** [comment]
The first Linux PR testing failed for completely unrelated reasons, so I triggered it again. But in the second invocation I forgot to mention the PR in the main repo, so it was verifying the `gyb`-generated files against the current version in there (which obviously failed), so now I triggered Linux PR testing for a third time. I should have maybe mentioned that in the trigger comments.

**Pull request merged**
