### PR TITLE
Add validation that all syntax collections end with `ListSyntax`

### PR DESCRIPTION
**Pull request by ahoppen**
This didn’t catch anything but it’s a validation I wanted to add.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]
> This didn’t catch anything but it’s a validation I wanted to add.

Does that mean you don't prefer `ListSyntax` for eg. `EffectsArgumentsSyntax` and `StringLiteralSegments`? Say `EffectsArgumentListSyntax` and `StringSegmentListSyntax`?

**Comment by ahoppen** [comment]
Actually, I just thought about it again and decided to rename all other collections (except `UnexpectedNodes`) to also have `List` suffix for consistency.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift-stress-tester/pull/243

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-stress-tester/pull/243

@swift-ci Please test Windows

**Review by kimdv — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
