### PR TITLE
Incorporate Doug’s macro examples in swift-syntax/Examples

### LINKED ISSUE #2026: Incorporate Doug’s macro examples in swift-syntax/Examples
https://github.com/DougGregor/swift-macro-examples is a great collection of macros. We should move them to the Examples folder in swift-syntax to give them more exposure and make sure they build with recent swift-syntax versions.

### PR DESCRIPTION
**Pull request by Matejkob**
This PR consists of two main commits.

1. **Incorporating Code and Renaming Targets**:
    - Introduced new targets in the `Examples` package, organized as follows:
    ```
    Examples
     ├─ Sources
     |   └─ MacroExamples
     |       └─ Implementation (Contains macro target `MacroExamplesImplementation`)
     |       └─ Interface (Contains target `MacroExamplesInterface`)
     |       └─ Playground (Contains executable target `MacroExamplesPlayground`)
     └─ Tests
         └─ MacroExamples
             └─ Implementation (Contains test target `MacroExamplesImplementationTests`)
    ``` 
    The new target names correspond to the original ones as:
      - `MacroExamplesPlugin` -> `MacroExamplesImplementation`
      - `MacroExamplesLib` -> `MacroExamplesInterface`
      - `MacroExamples` -> `MacroExamplesPlayground`
      - (newly added) -> `MacroExamplesImplementationTests`

    I believe the new naming convention and directory structure are more intuitive, especially for newcomers. However, I'm always open to feedback and discussion ❤️.
    
    - Transferred Doug's code to `swift-syntax/Examples` and updated references in the `#externalMacro` to the new module names.
    - Run `swift-format` to ensure consistent coding style.

2. **Fixing Errors and Warnings**:
    - Made essential changes to ensure that the macro examples build successfully in the latest environment.

For future improvements, I have several ideas to enhance the clarity and consistency of these examples, especially for newcomers. There are some inconsistencies in the macro creation process and our test methods could benefit from the latest APIs for faster and more consistent execution. We'll also address gaps in documentation. These improvements will be tackled in subsequent PRs, as discussed in #2026.

Resolves #2026.

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Oh, looks like the macros are actually buggy and the issues are being caught by [RawSyntax Validation](https://github.com/apple/swift-syntax/blob/main/CONTRIBUTING.md#rawsyntax-validation). In particular, the issue that I’m seeing is that AddAsyncMacro.swift:122 needs to be changed to the following, because the async specifier needs to be an `async` keyword and not an identifier with the text `async`. 

```swift
FunctionEffectSpecifiersSyntax(leadingTrivia: .space, asyncSpecifier: .keyword(.async), throwsSpecifier: isResultReturn ? .keyword(.throws) : nil)  // add async
```

You should be able to reproduce the failures locally by replacing the check for `SWIFTSYNTAX_ENABLE_RAWSYNTAX_VALIDATION` by `true` as described in [CONTRIBUTING.md](https://github.com/apple/swift-syntax/blob/main/CONTRIBUTING.md#rawsyntax-validation) and then building the examples. @Matejkob, could you check if there are more cases like this?

**Comment by Matejkob** [comment]
> Oh, looks like the macros are actually buggy and the issues are being caught by [RawSyntax Validation](https://github.com/apple/swift-syntax/blob/main/CONTRIBUTING.md#rawsyntax-validation). In particular, the issue that I’m seeing is that AddAsyncMacro.swift:122 needs to be changed to the following, because the async specifier needs to be an `async` keyword and not an identifier with the text `async`.
> 
> ```swift
> FunctionEffectSpecifiersSyntax(leadingTrivia: .space, asyncSpecifier: .keyword(.async), throwsSpecifier: isResultReturn ? .keyword(.throws) : nil)  // add async
> ```
> 
> You should be able to reproduce the failures locally by replacing the check for `SWIFTSYNTAX_ENABLE_RAWSYNTAX_VALIDATION` by `true` as described in [CONTRIBUTING.md](https://github.com/apple/swift-syntax/blob/main/CONTRIBUTING.md#rawsyntax-validation) and then building the examples. @Matejkob, could you check if there are more cases like this?

Thanks @ahoppen for the heads up and the quick fix suggestion! I've put in the change you mentioned and fingers crossed it'll work now.

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
Ah, and now the new files need to be formatted according to our style guide. Could you run `./format.py`?

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
Oh, I knew that this could theoretically happen because swift-format can’t fix all the formatting issues it detects, but it’s the first time that we actually hit a case where you needed to manually format something to make swift-format happy.

**Comment by Matejkob** [comment]
The test on Linux has failed, which is quite understandable since macros are not yet supported on this platform, are they?

Should we restrict macro examples to macOS only with `#if os(macOS)`, or do we have another approach for such cases?

**Comment by ahoppen** [comment]
Yes, we need to guard it with `#if os(macOS)`

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by Matejkob** [comment]
I don't have much experience developing packages for multiple platforms, so I'm not sure if the implemented solution will work. I've only guarded the target declarations in the package manifest. 🤞that we don't need to guard the whole implementation.

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Review by ahoppen — APPROVED** [review]

**Pull request merged**
