### PR TITLE
[build-script] Unify configuration params into one toolchain param

### PR DESCRIPTION
**Pull request by ahoppen**
This shifts the paradigm of the build script from specifying every executable manually to building SwiftSyntax using an existing toolchain. This goes in sync with building SwiftSyntax using `swift_build_support` in the main Swift repository.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test and merge

**Comment by ahoppen** [comment]
Let’s try again, now that the bot for SwiftSyntax PR testing has been updated.

@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/27934

@swift-ci Please test

**Comment by ahoppen** [comment]
Re-triggering due to network outage.

https://github.com/apple/swift/pull/27934

@swift-ci Please test

**Pull request merged**
