### PR TITLE
Add some structure to Package.swift

### PR DESCRIPTION
**Pull request by ahoppen**
Package.swift has been pretty unstructured so far and it was hard to find targets. I hope that this new formatting makes it a little easier to read. It does not change any target definition, just moves them around.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Review by kimdv — APPROVED** [review]

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
