### PR TITLE
Add 'package' access modifier contextual keyword

### PR DESCRIPTION
**Pull request by elsh**
Resolves rdar://103462581

### CODE REVIEW

**Comment by bnbarham** [comment]
LGTM, though note that Alex just copied this back into swift itself, so you'll need to add it there as well. The plan is to parse these more generally on the swift-syntax side, so this type of update won't be necessary in the future.

**Comment by elsh** [comment]
@swift-ci smoke test

**Comment by elsh** [comment]
@swift-ci test

**Comment by elsh** [comment]
@swift-ci test

**Review by bnbarham — APPROVED** [review]
Could you add `package` to `ContextualDeclKeyword` as well?

**Pull request merged**
