### PR TITLE
Add @_used and @_section attributes to match #65901

### PR DESCRIPTION
**Pull request by kubamracek**
See <https://github.com/apple/swift/pull/65901>.

### CODE REVIEW

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
Hi @kubamracek 👋

You need to run the code generation to get attribute kinds updated with your changes.
You can read about it here: https://github.com/apple/swift-syntax/blob/main/CodeGeneration/README.md

**Comment by kubamracek** [comment]
@kimdv Thanks for the info, I actually did run the regenerate step, but the SimpleDeclAttributes seem to simply have no effect (no need?) on the generated swift files?

**Comment by kubamracek** [comment]
...which made me realize that `@_used` is supposed to be an SimpleDeclAttribute, but `@_section` isn't and it's supposed to have arguments, so I need to do some more work here :)

**Comment by kubamracek** [comment]
@swift-ci please test

**Comment by kubamracek** [comment]
@swift-ci please test

**Review by ahoppen — COMMENTED** [review]
Hey Kuba,

Thanks for updating the parser. And it indeed looks like we are no longer using `DECL_ATTR_KINDS`. I’m removing it a follow-up PR.

Could you add a test case for `@_used` and `@_section`, e.g. in AttributeTests.swift?

**Comment by ahoppen** [comment]
And I’m removing the code generation of decl modifiers and type attributes here: https://github.com/apple/swift-syntax/pull/1715

**Comment by DougGregor** [comment]
Do we need this at all? They can be parsed as custom attributes, and it's fine, right?

**Comment by ahoppen** [comment]
Ah, true. We would need if `@_used` and `@_section` were type attributes to disambiguate `@_used () -> Void` but that doesn’t appear to be the case.

**Comment by kubamracek** [comment]
Ha! So I don't even need the parser changes (section attr takes a string argument), and I can just close this PR?

**Comment by ahoppen** [comment]
Yes, looks like it.

**Pull request closed without merging**
