### PR TITLE
Migrate to use Python 3

### PR DESCRIPTION
**Pull request by dduan**
Migrate Python code to Python 3 by:

1. update scripts' shebang
2. migrate syntax in Python modules
3. delete unnecessary imports

### CODE REVIEW

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
Ah, I see this one is mutually dependent with `apple/swift`....

**Comment by ahoppen** [comment]
Thanks for tackling this 🙏 

Yes, you would also need to update the files in `apple/swift/utils/gyb_syntax_support` to Python 3 because we import those from apple/swift-syntax

**Comment by dduan** [comment]
@ahoppen Everything in `apple/swift` should be Python 3 compatible. If I'm not mistaken, the problem is when a script is invoked as an executable as opposed to a Python module, the script will invoke whatever interpreter the OS chooses according to the shabang. In our case, `utils/gyb` has `python`, and I'm updating it to `python3` [in apple/swift](https://github.com/apple/swift/pull/42086). But that PR won't fully pass CI because it's running tests in this repo, and running into the same shebang problems addressed in this PR.

**Comment by ahoppen** [comment]
That sounds like you need to invoke cross-repo PR testing by mentioning the PR you want to test in conjunction with this one. Let’s see if it works.

https://github.com/apple/swift/pull/42086
@swift-ci Please test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test Linux Platform

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci Please test Linux

**Comment by dduan** [comment]
@swift-ci test

**Comment by dduan** [comment]
https://github.com/apple/swift/pull/42086
@swift-ci test

**Comment by dduan** [comment]
Alright. All green in both repos now.

**Review by ahoppen — APPROVED** [review]
Woohoo. This is great 🥳 Thanks for tackling this. It was long overdue

**Comment by dduan** [comment]
I merged the PR in `apple/swift`. I imagine PRs here will start failing unless we merge this.

**Comment by rintaro** [comment]
Merged to unblock the ci

**Pull request merged**
