### PR TITLE
[5.9] Add bazel configuration

### PR DESCRIPTION
**Pull request by keith**
This allows bazel users to depend on these libraries directly through the SwiftSyntax repo instead of everyone having to provide their own duplicate BUILD files. Since swift-syntax is pretty uniform this is setup using a simple bazel macro that uses the conventions of swiftpm to setup each library. This also includes a bazel target for always building a library with optimizations which can be useful if you want the improved performance and aren't trying to debug swift-syntax itself.

(cherry picked from commit 0a73615ca69ca299300557f57f60a51794172113)

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
Thanks!

**Comment by keith** [comment]
@swift-ci please test macOS platform

**Comment by keith** [comment]
@swift-ci please test windows platform

**Comment by keith** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Comment by DougGregor** [comment]
@swift-ci please clean test Windows

**Pull request merged**
