### PR TITLE
Remove `recover` methods from the parser

### PR DESCRIPTION
**Pull request by ahoppen**
Instead of sticking unexpected tokens into `errorTokens` of a `CodeBlock`, we should be putting them into the tree as unexpected nodes, where they can be diagnosed. These unexpected nodes are typically created by `Parser.expect` calls.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/60847

@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by CodaFi — APPROVED** [review]
We'll take it for now. There's some tricky cases especially with extraneous right braces that this won't handle correctly.

**Pull request merged**
