### PR TITLE
Split actor declarations into their own nodes

### PR DESCRIPTION
**Pull request by DougGregor**

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/59989
@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/59989
@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/59989
@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/59989
@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/59989
@swift-ci please test

**Comment by DougGregor** [comment]
Subsumed by https://github.com/apple/swift-stress-tester/pull/180

**Pull request closed without merging**
