### PR TITLE
reject invalid arguments to nonisolated contextual keyword

### PR DESCRIPTION
**Pull request by sophiapoirier**
tidying and follow-up to https://github.com/apple/swift-syntax/pull/2306

### CODE REVIEW

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by sophiapoirier** [comment]
@swift-ci please test Windows

**Review by ahoppen — APPROVED** [review]
Thank you!

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Comment by sophiapoirier** [comment]
@swift-ci please test

**Pull request merged**
