### PR TITLE
Update SwiftSyntax to Swift 5.7

### PR DESCRIPTION
**Pull request by ahoppen**
Now that Xcode on CI nodes has been updated, we don’t need to support Swift 5.5 and 5.6 anymore.

- Increase swift-tools-version to 5.7 
- Convert to shorthand `if let` notation
  - I was able to do this using the script from https://github.com/apple/swift-syntax/pull/887
- Migrate generics to opaque parameter types (aka. `some` types)
  - This was quite a lot of manual work
- Remove `@frozen` attributes
  - These only existed as a workaround for a miscompute on Swift 5.5 and are no longer needed
- Remove functions that only existed for Swift 5.6 compatibility 
  - No longer needed

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by kimdv — APPROVED** [review]
WUHU!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
Since CI keeps failing for me on this one and I can’t reproduce the failure locally, I’m splitting this up to at least pinpoint which commit is causing the CI failure.

**Pull request closed without merging**
