### PR TITLE
[SE-0413] Typed throws: enable by default

### PR DESCRIPTION
**Pull request by DougGregor**
SE-0413 "Typed Throws" has been accepted. Enable it by default, dropping the experimental feature flag.

### CODE REVIEW

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/70677

@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/70677

@swift-ci please test

**Comment by DougGregor** [comment]
https://github.com/apple/swift/pull/70677

@swift-ci please test Windows

**Review by kimdv — APPROVED** [review]
🎊

**Pull request merged**
