### PR TITLE
[Macros] Unify PluginMessages.swift

### PR DESCRIPTION
**Pull request by rintaro**
Compiler use PluginMessages.swift in swift-syntax consistently.

### CODE REVIEW

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/67025
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/67025
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/67025
@swift-ci Please test

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/67025
@swift-ci Please test Windows

**Review by DougGregor — APPROVED** [review]

**Comment by rintaro** [comment]
https://github.com/apple/swift/pull/67025
@swift-ci Please test

**Pull request merged**
