### PR TITLE
[6.0] Make swift-syntax build without warnings

### PR DESCRIPTION
**Pull request by ahoppen**
- **Explanation**: swift-syntax currently emits warnings when building it. It should build free of warnings. Make a couple of adjustments to fix the warnings.
- **Scope**: Not really limited to a very specific area
- **Risk**: Moderate, affects multiple files but each change is pretty trivial.
- **Testing**: Verified that swift-syntax builds without warnings
- **Issue**: n/a
- **Reviewer**:   @bnbarham on https://github.com/apple/swift-syntax/pull/2558 and https://github.com/apple/swift-syntax/pull/2569

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/72621

@swift-ci Please test Windows

**Pull request merged**
