### PR TITLE
Improve debug description of syntax nodes

### PR DESCRIPTION
**Pull request by ahoppen**
This improves the description generated by the `debugDescription` function to something like the following which is easier to read IMO

```text
SourceFileSyntax
├─CodeBlockItemListSyntax
│ ╰─CodeBlockItemSyntax
│   ╰─MacroExpansionExprSyntax
│     ├─pound
│     ├─identifier("stringify")
│     ├─leftParen
│     ├─TupleExprElementListSyntax
│     │ ╰─TupleExprElementSyntax
│     │   ╰─InfixOperatorExprSyntax
│     │     ├─IntegerLiteralExprSyntax
│     │     │ ╰─integerLiteral("2")
│     │     ├─BinaryOperatorExprSyntax
│     │     │ ╰─binaryOperator("+")
│     │     ╰─IntegerLiteralExprSyntax
│     │       ╰─integerLiteral("3")
│     ╰─rightParen
╰─eof
```

Since we now have this nice representation, it also removes the conformances to `CustomReflectable` (deleting 3000 lines of code 🎉 ) and doing some new `CustomReflectable` hackery to make the debugger just print `debugDescription` and not try to print the node’s children itself. This way you an now do `po node` in the debugger to get the debug description from above, instead of having to do `e print(node.recursiveDescription)`

### CODE REVIEW

**Comment by DougGregor** [comment]
Beautiful!

**Review by DougGregor — APPROVED** [review]

**Review by bnbarham — APPROVED** [review]
> −3,206

Aw yeah, that's what I like to see!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by kimdv — APPROVED** [review]

**Review by kimdv — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by rintaro — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/65118

@swift-ci Please test Windows

**Comment by kimdv** [comment]
@swift-ci please test

**Pull request merged**
