### PR TITLE
[6.0][CompilerPlugin] Remove Foundation dependency

### PR DESCRIPTION
**Pull request by rintaro**
cherry-pick https://github.com/apple/swift-syntax/pull/2598/commits

* **Explanation**: When we want to use `swift-foundation` as a package dependency, since `Foundation` uses macros, it depends on `SwiftCompilerPlugin`. So `swift-syntax` should not depends on `Foundation`. Implement its own JSON coder, and use `read(2)`, `write(2)`, etc. for standard I/O communication
* **Scope**: Executable macro plugins
* **Risk**: Mid. New JSON coder is somewhat risky
* **Testing**: Added JSON encoding/decoding unit test cases. Passes current test-suite
* **Issue**: rdar://126714084
* **Reviewer**: Hamish Knight (@hamishknight) Alex Hoppen (@ahoppen)

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
@swift-ci Please test Linux

**Comment by rintaro** [comment]
@swift-ci Please test Linux

**Comment by rintaro** [comment]
@swift-ci Please test Linux

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
@swift-ci Please test Linux

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
@swift-ci Please test Linux

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
