### PR TITLE
[5.9] Add support for the copy operator and fix parsing issues around consume

### PR DESCRIPTION
**Pull request by gottesmm**
I will add the CCC later.

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]

**Comment by gottesmm** [comment]
apple/swift#66032 is the swift 5.9 commit.

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/66032

@swift-ci test

**Comment by gottesmm** [comment]
MacOS test failure is due to a slight difference in enablement flags on 5.9 vs main:

/home/build-user/swift/test/Sema/copy_expr_noimplicit_copy.swift:8:3: error: unexpected error produced: Can not use feature when experimental move only is disabled! Pass the frontend flag -enable-experimental-move-only to swift to enable the usage of this language feature
@_noImplicitCopy let x = Klass()
^

I just fixed that in the other PR

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/66032

@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/66032

@swift-ci test

**Pull request merged**
