### PR TITLE
Disallow where clause in generic argument list

### PR DESCRIPTION
**Pull request by ahoppen**
The where clause in the generic argument list hasn’t been supported for quite a few Swift releaeses. Don’t support it in the new parser.

### CODE REVIEW

**Comment by DougGregor** [comment]
IIRC, we still use this syntax in SIL

**Comment by ahoppen** [comment]
Since we don’t use SwiftSyntax to represent SIL, this shouldn’t be an issue though, right?

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/63602

@swift-ci Please test

**Comment by ahoppen** [comment]
I’m closing this because it’s unlikely we’ll be able to merge this anytime soon. Opened https://github.com/apple/swift-syntax/issues/1417 so we don’t forget about it.

**Pull request closed without merging**
