### PR TITLE
Order all imports lexicographically

### PR DESCRIPTION
**Pull request by natikgadzhi**
## Motivation
- Part of #2136

## Changes
- Adds `OrderedImports` rule to `.swift-format`
- Removes a trailing space in `format.py`
- Formats the codebase to comply with `OrderedImports`

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Review by kimdv — APPROVED** [review]

**Comment by natikgadzhi** [comment]
@kimdv, thank you for reviewing this! ❤️

**Review by ahoppen — APPROVED** [review]
Looks good to me. I just want to get a second opinion from @bnbarham and @rintaro before merging this.

**Review by bnbarham — APPROVED** [review]
Sounds good to me, thanks @natikgadzhi!

**Pull request merged**
