### PR TITLE
Remove generated note in header

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
Not sure why windows fails on this one 🤔

**Comment by compnerd** [comment]
```
CMake Error: File C:/Users/swift-ci/jenkins/workspace/swift-syntax-PR-windows/llvm-project/llvm/stdlib/public/Cxx/std/libstdcxx.modulemap does not exist.
CMake Error at C:/Users/swift-ci/jenkins/workspace/swift-syntax-PR-windows/swift/unittests/ClangImporter/CMakeLists.txt:1 (configure_file):
  configure_file Problem configuring file
```

CC: @egorzhdan @zoecarver

**Comment by compnerd** [comment]
This was caused by @hyp in apple/swift#64177

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift/pull/64241

@swift-ci please test Windows platform

**Review by ahoppen — APPROVED** [review]

**Pull request merged**
