### PR TITLE
Introduce a placeholder declaration to represent editor placeholders in member decl lists

### PR DESCRIPTION
**Pull request by ahoppen**
As suggested in https://github.com/apple/swift-format/issues/462

### CODE REVIEW

**Review by allevato — APPROVED** [review]
This is great, thanks!

I do like this better than the idea to use unexpected nodes, since it separates a case that's valid for formatting over one that's difficult to distinguish from other unexpected nodes.

**Comment by ahoppen** [comment]
Yes, I changed my mind after I posted the comment on the issue in swift-format 😉 This turned out to be simpler

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Pull request merged**
