### PR TITLE
[NFC] Updated the update-toolchain.py script to conform to the PEP8 formatting standard.

### PR DESCRIPTION
**Pull request by Rostepher**

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
I believe we can just delete this script. I just realized  that its invocation of `build-script.py` hasn’t been working since I migrated SwiftSyntax to `swift_build_support`. So apparently nobody is using it.

**Comment by Rostepher** [comment]
@ahoppen 

> I believe we can just delete this script. I just realized that its invocation of `build-script.py` hasn’t been working since I migrated SwiftSyntax to `swift_build_support`. So apparently nobody is using it.

Would you like me to close this then and open a new PR to remove the script?

**Comment by ahoppen** [comment]
> Would you like me to close this then and open a new PR to remove the script?

Sounds good to me.

**Pull request closed without merging**
