### PR TITLE
[NFC] Updated the build-script.py script to conform to the PEP8 formatting standard.

### PR DESCRIPTION
**Pull request by Rostepher**

### CODE REVIEW

**Comment by Rostepher** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
One minor thing: We are still doing a lot of path construction using string concatenation. I believe these should be migrated to `os.path.join`. But doesn’t need to be done as part of this PR.

**Comment by Rostepher** [comment]
@ahoppen 

> One minor thing: We are still doing a lot of path construction using string concatenation. I believe these should be migrated to `os.path.join`. But doesn’t need to be done as part of this PR.

I planned to address that some other things I noticed in follow-up PRs. Just laying the foundation now rather than dump one massive, untestable PR on your laps.

**Comment by ahoppen** [comment]
That’s very good with me!

**Pull request merged**
