### PR TITLE
Update swift-syntax

### PR DESCRIPTION
**Pull request by kimdv**
Depends on #1287

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Nice. Those variable decls are a lot easier to read.

Can we wait for https://github.com/apple/swift-syntax/pull/1253 to be merged before merging this PR? I’ve been trying to get that PR merged for a couple of days now and constantly faced merge conflicts in one of the repos it touches. 😢

**Comment by kimdv** [comment]
> Nice. Those variable decls are a lot easier to read.

A lot easier! 

> Can we wait for #1253 to be merged before merging this PR? I’ve been trying to get that PR merged for a couple of days now and constantly faced merge conflicts in one of the repos it touches. 😢

I will wait and update code-gen if needed :D

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/1253 is merged now so we can land this PR.

@swift-ci Please test

**Review by ahoppen — APPROVED** [review]
Thanks for this big update of CodeGeneration 🙏

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
Even tough we do a lot of `try!` 🫣
When #1287 is merged, we will update with a follow up PR

**Comment by ahoppen** [comment]
Yes, let’s try to get rid of the `try!` in follow-up PRs.

**Comment by kimdv** [comment]
@swift-ci please test

**Pull request merged**
