### PR TITLE
[5.8] Cherry-pick most changes from `main` to `release/5.8`

### PR DESCRIPTION
**Pull request by ahoppen**
There have been major API redesigns in swift-syntax in the last couple of weeks. To make transitioning clients to the new API easier, we are cherry-picking all of those changes to `release/5.8`. That way, only one adjustment is needed when updating to 5.8 instead of having to update when adopting 5.8 and requiring more significant changes when updating to 5.9.

The only PR that will not be cherry-picked to `release/5.8` is https://github.com/apple/swift-syntax/pull/1167 because it requires significant changes in apple/swift. @hborla Could you verify that I correctly reverted that patch in https://github.com/apple/swift-syntax/commit/841c0eccaa239af17a5e849290e3b3dbaabf98ff? I am fairly confident I did it correctly, but it’s always good to double-check.

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/63258
https://github.com/apple/swift-format/pull/479
https://github.com/apple/swift-stress-tester/pull/226

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/63258
https://github.com/apple/swift-format/pull/479
https://github.com/apple/swift-stress-tester/pull/226
https://github.com/apple/sourcekit-lsp/pull/702

@swift-ci Please test

**Review by hborla — APPROVED** [review]
The variadic generics revert looks right to me 👍

**Comment by ahoppen** [comment]
After some discussion we decided that this is too risky to cherry-pick into 5.8.

**Pull request closed without merging**
