### PR TITLE
Rename `LexerError` -> `TokenDiagnostic`

### PR DESCRIPTION
**Pull request by ahoppen**
`LexerError` has been the wrong name for this for two reasons:
- It could also contain warnings generated by the lexer
- It also contained errors about insufficient indentation that weren’t generated by the lexer

`TokenDiagnostic` is the best name I have found to describe what this is doing.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]
Works for me, thanks!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
