### PR TITLE
Remove `Keyword` suffix from Pound*

### LINKED ISSUE #1834: Drop `Keyword` suffix from `TokenKind.poundAvailableKeyword` etc.
Since we moved keywords into a dedicated case with an associated value, the pound keywords with their `Keyword` suffix seem a little out-of-place. We should drop the `Keyword` suffix.

### PR DESCRIPTION
**Pull request by kimdv**
Resolves #1834

companion PRs
https://github.com/apple/sourcekit-lsp/pull/764

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Thanks

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test windows

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/sourcekit-lsp/pull/764

@swift-ci please test windows

**Pull request merged**
