### PR TITLE
Prefer the first lexical error in a string literal segment

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #1480

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Thank you for your contribution. This looks great!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Could you format the files as described in https://github.com/apple/swift-syntax/blob/main/CONTRIBUTING.md#formatting?

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by cbjeukendrup** [comment]
When I try to build swift-format using `swift build -c release`, it fails with `error: 'swift-format': product 'SwiftParser' required by package 'swift-format' target 'swift-format' not found in package 'swift-syntax'.`. And when I use swift-format from HomeBrew, it touches some files that I had not modified. So I've committed only the changes to the file that I modified, so I hope it will be fine.

**Comment by ahoppen** [comment]
That's odd. How exactly are you building swift-format, which branch are you building and is your checkout up-to-date?

**Comment by cbjeukendrup** [comment]
It looks like I've just fixed it by removing `Package.resolved` from my `swift-format` folder. And indeed the self-built version of `swift-format` does not introduce unexpected changes. So everything seems fine now!

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
