### PR TITLE
Add missing parameters for gyb generation

### PR DESCRIPTION
**Pull request by kimdv**
Fixed some missing parameters that was introduced in #263

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Thanks for fixing this!

**Comment by ahoppen** [comment]
@swift-ci Please test and merge

**Comment by kimdv** [comment]
@ahoppen is this test / merge stuck or do I need to do something?

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Thanks for pinging me about it. Looks like CI didn’t run and I forgot about it. Sorry about that.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
