### PR TITLE
Remove the typealiases in SwiftSyntaxBuilder that refer to syntax nodes without the `Syntax` suffix

### PR DESCRIPTION
**Pull request by ahoppen**
In the past, before SwiftSyntaxBuilder shared the same syntax nodes with SwiftSyntax, it made sense for it to have its own syntax nodes and thus drop the `Syntax` suffix.

But since SwiftSyntaxBuilder is now just providing convenience initializers, it’s confusing to have two names to refer to the same type - the style was already pretty inconsitent in this code base. To make things consistent, drop the typealiases.

### CODE REVIEW

**Review by kimdv — APPROVED** [review]
Nice! 

It have always confused m with the typealias

**Review by bnbarham — APPROVED** [review]
Awesome, thanks Alex!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
