### PR TITLE
[5.9] Update BasicFormat

### PR DESCRIPTION
**Pull request by ahoppen**
Cherry-picks the following PRs to release/5.9, updating BasicFormat to a new version that produces source code which represents the same syntax tree when re-parsed for all passing `assertParse` test.

- https://github.com/apple/swift-syntax/pull/1547
- https://github.com/apple/swift-syntax/pull/1561
- https://github.com/apple/swift-syntax/pull/1558
- https://github.com/apple/swift-syntax/pull/1567
- https://github.com/apple/swift-syntax/pull/1568
- https://github.com/apple/swift-syntax/pull/1498
- https://github.com/apple/swift-syntax/pull/1569

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
