### PR TITLE
Rename `createUniqueName` to `makeUniqueName`.

### PR DESCRIPTION
**Pull request by rxwei**
As per Evolution comment: https://forums.swift.org/t/se-0382-second-review-expression-macros/63064/20

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
apple/swift#63962
@swift-ci please smoke test

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Comment by rxwei** [comment]
Update to define both as protocol requirements with each having a default implementation in terms the other.

**Comment by rxwei** [comment]
@swift-ci please smoke test

**Review by DougGregor — APPROVED** [review]

**Comment by rxwei** [comment]
@swift-ci please smoke test Linux

**Comment by rxwei** [comment]
@swift-ci please smoke test macOS

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
Windows failure is unrelated. Merging to get closer to SE-0382.

**Pull request merged**
