### PR TITLE
guard nonisolated(unsafe) by experimental feature

### PR DESCRIPTION
**Pull request by sophiapoirier**

### CODE REVIEW

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test macOS

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test macOS

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test Linux

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69725

@swift-ci please test Windows

**Pull request merged**
