### PR TITLE
Improve diagnostic in `testMissingArgumentToAttribute`

### PR DESCRIPTION
**Pull request by ahoppen**
This allows us to add fix-its that insert missing tokens. 

Fixes https://github.com/apple/swift-syntax/issues/821

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/61298

@swift-ci Please test macOS

**Pull request merged**
