### PR TITLE
Fix child name validation failures found by `testConsistentNamingOfChildren`

### PR DESCRIPTION
**Pull request by ahoppen**
As a rule of thumb, two children with the same type should have the same name.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by kimdv — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/561

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/561

@swift-ci Please test Linux

**Pull request merged**
