### PR TITLE
Fix Regression in Leading Unexpected Tokens for Declarations

### PR DESCRIPTION
**Pull request by CodaFi**
This was introduced while migrating their introducers from eat to expect in #748

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by bnbarham** [comment]
Will cause failures in https://github.com/apple/swift-syntax/pull/737, but they'll be easy to fix.

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Pull request merged**
