### PR TITLE
Updated CONTRIBUTING.md with fork/PR submission info

### PR DESCRIPTION
**Pull request by adammcarter**
To make it clear on how others can contribute to the project there's now a dedicated section on how to raise a PR including step by step instructions

From issue https://github.com/apple/swift-syntax/issues/2575

### CODE REVIEW

**Review by ahoppen — COMMENTED** [review]
Instead of duplicating Git-related information, I would prefer to link to existing documentation that’s probably better and has more links to dive deeper. GitHub seems to have a fairly good page of how to fork a repo. If you think this page would have helped you as well, I’d prefer to link to that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

**Comment by adammcarter** [comment]
> I would prefer to link to existing documentation ...

Good shout! I've updated the file with your suggestion 👌🏻

**Review by ahoppen — APPROVED** [review]
Thanks 👍🏽

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
