### PR TITLE
Added unit test for testing the removal of an attached macro

### PR DESCRIPTION
**Pull request by SomeRandomiOSDev**
Adds an additional unit test to test the removal of an attached attribute

### CODE REVIEW

**Comment by ahoppen** [comment]
Out of curiosity: What made you write this test case? Is there some kind of behavior you wanted to verify?

**Comment by SomeRandomiOSDev** [comment]
Yeah, originally I developed this unit test to fix an issue that I had noticed [here](https://github.com/pointfreeco/swift-macro-testing/pull/12) that had used a version of `FixItApplier` from a previous `swift-syntax` version, but since this type was refactored and made public it seems it would be good to have this in place to ensure that replacing nodes in this manner succeeds as expected.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by ahoppen** [comment]
Sorry for not merging this @SomeRandomiOSDev. I forgot about this. Closing this since @Matejkob has opened a PR that cherry-picks this and resolves the merge conflicts.

**Pull request closed without merging**
