### PR TITLE
Update parser-diags.swift test

### PR DESCRIPTION
**Pull request by theblixguy**
The diagnostic for confusables was updated in https://github.com/apple/swift/pull/33105.

### CODE REVIEW

**Comment by theblixguy** [comment]
cc @rintaro @akyrtzi

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Comment by theblixguy** [comment]
Could you please re-run the tests? There was a typo in the diagnostic message which I have fixed (sorry about that).

**Comment by varungandhi-apple** [comment]
@swift-ci Please test

**Pull request merged**
