### PR TITLE
[6.0][bazel] Add new targets

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by keith** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@keith Could you please add a CCC template for PRs targeting `release/6.0` as described in https://forums.swift.org/t/swift-6-0-release-process/70220#pull-requests-for-release-branch-8?

**Comment by keith** [comment]
oops, thanks, updated the description here. would you like to review the bazel-only file changes going into this branch moving forward?

**Comment by ahoppen** [comment]
We should get an approval from one of the branch managers. Going forward, it's probably easiest if you put up the PR and we'll take care of merging it.

**Pull request merged**
