### PR TITLE
Make generic API for binary operators

### PR DESCRIPTION
**Pull request by kitasuke**
## Overview

Added generic API for binary operators so that it can make `TokenSyntax` for any binary operator

### CODE REVIEW

**Comment by kitasuke** [comment]
I'm new to gyb, but can we have python file which has a list of binary operators in SwiftSyntax side so that we can generate gyb files?

**Comment by akyrtzi** [comment]
What do you see the benefit of naming each one and not just use a generic version:
```

**Comment by akyrtzi** [comment]
What do you see the benefit of naming each one and not just use a generic version:
```
SyntaxFactory.makeBinaryOperator("+=")
```
?
We'd need a generic version anyway for custom operators, and seeing the operator written out may actually be a bit more readable. We could also have this do a sanity check that the string really contains an operator.

**Comment by kitasuke** [comment]
I thought reserved binary operators can have explicit api, but generic one looks much better.

**Comment by akyrtzi** [comment]
@swift-ci Please test

**Pull request merged**
