### PR TITLE
[borrow-expr] Initial commit for borrow expo

### PR DESCRIPTION
**Pull request by gottesmm**
Just an initial commit.

### CODE REVIEW

**Comment by gottesmm** [comment]
apple/swift#62742

@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/62742

@swift-ci test

**Comment by gottesmm** [comment]
A letter 'd' snuck into my test file due to vim issues = (. Restarting testing.

**Review by ahoppen — APPROVED** [review]

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/62742

@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/62742

@swift-ci test

**Pull request merged**
