### PR TITLE
[5.7] Update to support shorthand if-let

### PR DESCRIPTION
**Pull request by ahoppen**
Companion of https://github.com/apple/swift/pull/61263

Fixes https://github.com/apple/swift-syntax/issues/816

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/61263

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/61263

@swift-ci Please test

**Review by CodaFi — APPROVED** [review]

**Review by airspeedswift — APPROVED** [review]

**Comment by allevato** [comment]
Are there plans for a 0.50700.1 release that includes this? That would resolve https://github.com/apple/swift-format/issues/409.

**Comment by ahoppen** [comment]
Yes, absolutely. I need to wait for a toolchain snapshot to be created so I’ve got they parser library that I can include in the release. I still need to figure out what it takes to create a 5.7 snapshot toolchain as we don’t seem to be building them at this moment anymore.

**Pull request merged**
