### PR TITLE
[5.9] Fix xctskip warning

### PR DESCRIPTION
**Pull request by kimdv**
Cherry picks #1497

I tought it might be a simple one to get in. Just so we don't make a release with a warning in

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by kimdv** [comment]
@swift-ci please test Windows

**Comment by kimdv** [comment]
Closing this as it's merged in https://github.com/apple/swift-syntax/pull/1556

**Pull request closed without merging**
