### PR TITLE
Add tests for already fixed issues

### PR DESCRIPTION
**Pull request by omochi**
I started to fix issues #632 and #634.
But it seems to be already fixed.

I added test cases for them.

### CODE REVIEW

**Comment by ahoppen** [comment]
Oh, nice. Those are always the best issues that have already been fixed. 👍 

I just merged https://github.com/apple/swift-syntax/pull/641 that changes the `allowErrors` parameter of `AssertParse` to instead require specifying the produced diagnostics. Could you update your PR for that API? 

You don’t need to worry about the quality of the generated diagnostics at this point, I’ll do some basic work on general diagnostic quality in the week(s). If you think the diagnostics are sub-optimal, just add a FIXME for now.

**Comment by omochi** [comment]
OK, I edit my PR to use new checking for specific diagnostics.

**Comment by omochi** [comment]
@ahoppen I updated PR.
In both cases, diagnostics from parser is weird.
I wrote FIXME about it.

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Pull request merged**
