### PR TITLE
Display actual expanded source, not expected source

### PR DESCRIPTION
**Pull request by JosephDuffy**
While using this function I was confused by the error message. I think it should include the actual expansion, not what's expected?

I also renamed the variable to try and make it a little clearer and (assuming this is correct) prevent a mistake like this again. This was done in 3c46da3712dec11e5d485c96b6b7d9d40b7c8f25 so can be easily reverted.

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Thank you. What a stupid mistake. Could you also open a second PR targeting the `release/5.9` branch so that we can also get it fixed for the Swift 5.9 release?

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by JosephDuffy** [comment]
> Thank you. What a stupid mistake. Could you also open a second PR targeting the `release/5.9` branch so that we can also get it fixed for the Swift 5.9 release?

It was a bit confusing when I saw the message 😅 I'm glad I could fix it 😄

I've opened #1918.

**Comment by ahoppen** [comment]
Thank you @JosephDuffy!

**Pull request merged**
