### PR TITLE
Revert "Add `ExtensionDecl` test"

### PR DESCRIPTION
**Pull request by eeckstein**
Reverts apple/swift-syntax#331

It breaks the build: https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-18_04-long-test//6392/console

### CODE REVIEW

**Comment by eeckstein** [comment]
@swift-ci smoke test

**Comment by eeckstein** [comment]
@swift-ci test

**Review by kimdv — APPROVED** [review]

**Comment by kimdv** [comment]
@eeckstein I think you also need to revert https://github.com/apple/swift/pull/40358

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/331#issuecomment-986793305:

> CI just got very unlucky with its checkout. It was started at exactly the same time that the PRs were merged and picked up #331 but not [apple/swift#40358](https://github.com/apple/swift/pull/40358). It should be fixed in the next build.

**Pull request closed without merging**
