### PR TITLE
[5.10] Remove `@_implementationOnly` annotations

### PR DESCRIPTION
**Pull request by ahoppen**
* **Explanation**: Building swift-syntax with a Swift 5.10 compiler produces warnings that “Using '@_implementationOnly' without enabling library evolution for 'SwiftSyntax' may lead to instability during execution”. We want swift-syntax to build without warnings. To fix this, remove the `@_implementationOnly` annotations and replace them with `private import` if the host compiler is Swift ≥5.11.
* **Scope**: `@_implementationOnly` imports of Foundation-like modules in `SwiftSyntaxCompilerPlugin` and `SwiftSyntax`
* **Risk**: Any issues from this would be found at build time
* **Testing**: Tested that swift-syntax still builds and tests pass.
* **Issue**: rdar://115910675
* **Reviewer**:  @rintaro on https://github.com/apple/swift-syntax/pull/2429

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by airspeedswift — APPROVED** [review]

**Pull request merged**
