### PR TITLE
Cherry-pick PRs from `main` to `release/5.9`

### PR DESCRIPTION
**Pull request by ahoppen**
This cherry-picks the following PRs to `release/5.9`, effectively bringing `release/5.9` up-to-date with `main`

- https://github.com/apple/swift-syntax/pull/1462
  - Only modifies a test utility that is not part of the toolchain, so very low risk and useful to trace performance problems
- https://github.com/apple/swift-syntax/pull/1436
  - This fixes minor parsing bugs found by [#1339](https://github.com/apple/swift-syntax/pull/1339), so we should take it into 5.9
- https://github.com/apple/swift-syntax/pull/1456
  - Fixes a known bug that we previously allows `=` with unbalanced whitespace
- https://github.com/apple/swift-syntax/pull/1457
  - Cleanup with a slight performance boost that is needed for regex lexing
- https://github.com/apple/swift-syntax/pull/1440
  - Generally improves our structure to represent versions in the SwiftSyntax tree. I wouldn’t want to ship 5.9 with the old representation where a float was used to represent the major and minor version. Also fixes a parser bug where we would expect arbitrary float literals (like `1.0e2` for the major version) and hex integer literals for the patch version
- https://github.com/apple/swift-syntax/pull/1442
  - Needed for macros AFAICT
- https://github.com/apple/swift-syntax/pull/1445
  - Low risk, improves diagnostics
- https://github.com/apple/swift-syntax/pull/1422
  - Fixes an issue that we had the wrong code-generated files checked in
- https://github.com/apple/swift-syntax/pull/1444
  - Low risk, improves diagnostics
- https://github.com/apple/swift-syntax/pull/1441
  - Improves what will be highlighted in a diagnostic from a single character to an entire token. Dramatically improves how the highlight looks IMO.
- https://github.com/apple/swift-syntax/pull/1380
  - We weren’t diagnosing editor placeholders as error. That was bad. This fixes it.
- https://github.com/apple/swift-syntax/pull/1429
  - Low risk, improve diagnostics
- https://github.com/apple/swift-syntax/pull/1435
  - Fixes a build-time warning about a non-excluded CMakeLists.txt. Super-low risk
- https://github.com/apple/swift-syntax/pull/1339
  - All the code added by this is behind `#if` and makes cherry-picking a lot easier because this touches a lot. Thus, low risk
- https://github.com/apple/swift-syntax/pull/1427
  - If we are not willing to enable these assertions (or after this PR `precondition`s) now, I think we will never have the guts to do so. So let’s get it in now while we still have time until the real release.
- https://github.com/apple/swift-syntax/pull/1432
  - Similar to above, we should enable these assertions for 5.9. Also this is lower risk because it only affects `Release+Assert` builds, not plain release builds.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Comment by kimdv** [comment]
To the editor placeholder we also need to cherry pick in the swift repo. If that also have a 5.9 branch

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/64805

@swift-ci Please test

**Comment by ahoppen** [comment]
> To the editor placeholder we also need to cherry pick in the swift repo. If that also have a 5.9 branch

Thanks for keeping track of things. I forgot about that. I opened https://github.com/apple/swift/pull/64805.

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/64805

@swift-ci Please test macOS

**Pull request merged**
