### PR TITLE
[6.0] Add option to install targets even when not top level

### PR DESCRIPTION
**Pull request by ahoppen**
- **Explanation**: Also add namespaced targets for any exported target to facilitate find_package and FetchContent both using the same target names.
- **Scope**: CMake build
- **Risk**: Any issues will be caught at build-time
- **Testing**: n/a
- **Issue**: n/a
- **Reviewer**:   @bnbarham on https://github.com/apple/swift-syntax/pull/2628

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-package-manager/pull/7520
https://github.com/apple/sourcekit-lsp/pull/1213

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-package-manager/pull/7520
https://github.com/apple/sourcekit-lsp/pull/1213

@swift-ci Please test

**Comment by bnbarham** [comment]
Thanks (and sorry for not cherry-picking)

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/73392

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/73392

@swift-ci Please test Windows

**Pull request merged**
