### PR TITLE
Implement parsing for  `_forget` statement

### PR DESCRIPTION
**Pull request by kavon**
rdar://105795731

per SE-390 (under review, hence underscored) https://github.com/jckarter/swift-evolution/blob/noncopyable-structs-and-enums/proposals/0390-noncopyable-structs-and-enums.md#suppressing-deinit-in-a-consuming-method

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
LGTM

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test and merge

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
hm.
```
Detected unexpected failure: Timed out waiting for SourceKit response
  request: CursorInfo in /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/StressTesterToolTests/test.swift at offset 5 with args: /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/StressTesterToolTests/test.swift
```

**Comment by kavon** [comment]
@swift-ci please test

**Comment by kavon** [comment]
@swift-ci please test

**Pull request merged**
