### PR TITLE
🍒 guard nonisolated(unsafe) by experimental feature

### PR DESCRIPTION
**Pull request by sophiapoirier**

### CODE REVIEW

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test Windows

**Review by hborla — APPROVED** [review]

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
Explanation: bug fixes and functional completion for static concurrency opt-out mechanism `nonisolated(unsafe)`
Scope: the scope is corrections to a language change already included behind an experimental feature flag
Issue: none
Risk: low risk given that functionality is guarded behind an experimental feature flag
Testing: unit tests included
Reviewer: @hborla

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test Windows

**Comment by sophiapoirier** [comment]
https://github.com/apple/swift/pull/69833

@swift-ci please test Windows

**Pull request merged**
