### PR TITLE
Remove deprecated methods

### PR DESCRIPTION
**Pull request by ahoppen**
Now that we have branched for Swift 5.8, we can remove all deprecated methods on main.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Holding this back to make cherry-picking changes from main to release/5.8 easier.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by bnbarham** [comment]
> −9,559

That's the kind of number I like to see :). Thanks Alex!

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/63387

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/63387

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/63387

@swift-ci Please test

**Pull request merged**
