### PR TITLE
Replace where parameter in consume(if:) and friends by `allowTokenAtStartOfLine`

### PR DESCRIPTION
**Pull request by ahoppen**
rdar://103774625

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by bnbarham** [comment]
You might be better off combining this with https://github.com/apple/swift-syntax/pull/1224 to avoid another round of conflicts 😅

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
