### PR TITLE
[docs] add several example adopters to readme.

### PR DESCRIPTION
**Pull request by nkcsgexi**

### CODE REVIEW

**Comment by nkcsgexi** [comment]
cc: @ kishikawakatsumi and @inamiy

**Comment by inamiy** [comment]
Thank you for listing 🎉 

I also recommend @kishikawakatsumi 's [swiftfmt](https://github.com/kishikawakatsumi/swiftfmt) to be listed in README.
There is also another playground at https://swiftfmt.kishikawakatsumi.com .

**Comment by inamiy** [comment]
And FYI https://github.com/omochi/SwiftPack is probably the very first example I saw using SwiftSyntax by @omochi

**Comment by nkcsgexi** [comment]
@inamiy Thanks for the suggestions! I've updated this PR to include @omochi's SwiftPack to the example list. I haven't included @kishikawakatsumi 's swiftfmt because there is already a formatter in the list. We want to cover as diversified domains as possible.

**Comment by omochi** [comment]
Wow! thanks!

**Pull request merged**
