### PR TITLE
Fix child name validation failures found by `testMultipleKeywordChoicesNaming`

### PR DESCRIPTION
**Pull request by ahoppen**
If a token only has keyword token choices, its name should end with `Keyword`.

### CODE REVIEW

**Review by kimdv — APPROVED** [review]

**Review by bnbarham — APPROVED** [review]

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Pull request merged**
