### PR TITLE
Rename `leftSquareBracket` and `rightSquareBracket`

### LINKED ISSUE #1749: Rename `TokenKind.leftSquareBracket` to `TokenKind.leftSquare`
In `TokenKind`, we have

```swift
  case leftAngle
  case leftBrace
  case leftParen
  case leftSquareBracket
```

`leftSquareBracket` is the outlier here and should be `leftSquare`. Same for `rightSquareBracket`.

### PR DESCRIPTION
**Pull request by kimdv**
Resolves #1749

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]
Thanks for the quick fix, @kimdv. LGTM

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
@swift-ci please test windows

**Pull request merged**
