### PR TITLE
No longer require trailing space after expression-like keywords

### PR DESCRIPTION
**Pull request by fwcd**
Companion PR to apple/swift#60502.

### CODE REVIEW

**Comment by fwcd** [comment]
https://github.com/apple/swift/pull/60502

@swift-ci please test

**Comment by fwcd** [comment]
https://github.com/apple/swift/pull/60502

@swift-ci please test

**Comment by fwcd** [comment]
https://github.com/apple/swift/pull/60502

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
I modified `BuildableCollectionNodes` to no longer use `SyntaxFactory`, so I think you need to rebase on top of that.

**Comment by fwcd** [comment]
https://github.com/apple/swift/pull/60502

@swift-ci please test

**Comment by fwcd** [comment]
https://github.com/apple/swift/pull/60502

@swift-ci please test

**Pull request merged**
