### PR TITLE
Change all library types to automatic

### PR DESCRIPTION
**Pull request by ahoppen**
`automatic` and `static` currently have the same behavior in SwiftPM and we should allow flexibility here, there’s no reason to specify that the libraries need to be `static`.

### CODE REVIEW

**Review by kimdv — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by kimdv — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test windows

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
