### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]
Thank you.

CC @natikgadzhi just FYI, you didn’t update swift-syntax to use the renamed API.

**Comment by natikgadzhi** [comment]
Oh yikes. ;( Sorry, @ahoppen and @kimdv.

**Comment by ahoppen** [comment]
Not a problem at all. Just wanted to keep you in the loop.

**Pull request merged**
