### PR TITLE
Add @globalConstructor attribute

### PR DESCRIPTION
**Pull request by keith**
https://github.com/apple/swift/pull/62428
https://forums.swift.org/t/pitch-globalconstructor/61901/3

### CODE REVIEW

**Comment by keith** [comment]
https://github.com/apple/swift/pull/62428
@swift-ci please test

**Comment by keith** [comment]
https://github.com/apple/swift/pull/62428
@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by keith** [comment]
https://forums.swift.org/t/pitch-globalconstructor/61901/3

**Comment by keith** [comment]
https://forums.swift.org/t/pitch-globalconstructor/61901

**Pull request closed without merging**
