### PR TITLE
Merge `spacedBinaryOperator` and `unspacedBinaryOperator`

### PR DESCRIPTION
**Pull request by ahoppen**
We can only merge `spacedBinaryOperator` and `unspacedBinaryOperator` because the prefix/postfix distinction is not implemented in SwiftOperators. We don’t want to implement the distinction between prefix/infix/postfix operators in SwiftOperators there because it’s nice to get the prefix/postfix distinction without having to run the semantic SwiftOperator.

rdar://103774663

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/472
https://github.com/apple/swift-stress-tester/pull/221

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/472
https://github.com/apple/swift-stress-tester/pull/221 
https://github.com/apple/swift/pull/62961

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/472
https://github.com/apple/swift-stress-tester/pull/221
https://github.com/apple/swift/pull/62961

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/472
https://github.com/apple/swift-stress-tester/pull/221
https://github.com/apple/swift/pull/62961

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-format/pull/472
https://github.com/apple/swift-stress-tester/pull/221
https://github.com/apple/swift/pull/62961

@swift-ci Please test macOS

**Pull request merged**
