### PR TITLE
Merge SwiftSyntax and SwiftParser

### PR DESCRIPTION
**Pull request by ahoppen**
The types from the `SwiftParser` module were incorporated in the `SwiftSyntax` module. This reduces the number of imports clients need to add to use SwiftSyntax and allows further performance optimizations if the parser can benefit from whole module optimization with the definition of the syntax nodes.

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/71051

@swift-ci Please test

**Comment by allevato** [comment]
Can you compare the WMO build times of SwiftSyntax+SwiftParser before this change and SwiftSyntax after this change? This looks like it would be adding more work to the already long WMO build for SwiftSyntax, but if the new module builds faster than the sum of the two, then it's still a win?

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/71051
https://github.com/apple/sourcekit-lsp/pull/1029

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/71051
https://github.com/apple/sourcekit-lsp/pull/1029

@swift-ci Please test

**Comment by ahoppen** [comment]
apple/swift#71051
apple/sourcekit-lsp#1029

@swift-ci Please test

**Comment by ahoppen** [comment]
apple/swift#71051
apple/sourcekit-lsp#1029

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/71051
https://github.com/apple/sourcekit-lsp/pull/1029

@swift-ci Please test Windows

**Pull request closed without merging**
