### PR TITLE
Remove the last lit test

### PR DESCRIPTION
**Pull request by ahoppen**
We only had a single lit test left, which was testing the integration of the macro plugin with the compiler. That testing should be covered by us building the macro examples in the `Examples` package, so it’s not needed anymore.

rdar://114469622

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/68364

@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Review by kimdv — APPROVED** [review]

**Review by Matejkob — COMMENTED** [review]
I'm wondering if we still need the [`ExamplePlugin` target in the `Examples` package](https://github.com/apple/swift-syntax/tree/main/Examples/Sources/ExamplePlugin) - was it mainly used for lit tests, and is it now a bit redundant with `MacroExamples`?

**Comment by ahoppen** [comment]
Yes, I think merging the two targets would make sense. Could you be interested in doing that, @Matejkob?

**Comment by Matejkob** [comment]
Sure, I've added an issue for that.

**Pull request merged**
