### PR TITLE
Fixed expected assignment instead of comparison in function parameters

### PR DESCRIPTION
**Pull request by CippoX**
I am unsure of how to implement the FixIt.

### CODE REVIEW

**Comment by kimdv** [comment]
Hi @CippoX 

I've also been working on this 😅

**Comment by CippoX** [comment]
Hi @kimdv, my bad, I should have noticed you PR 😅, would you mind to take a look at this and tell me if I was on the right path?

**Comment by kimdv** [comment]
No problem! 
Feel free to review my PR. 

Our solution is more or less the same. Slight different approaches for some things. 
It might just be me not knowing all APIs yet.

**Comment by CippoX** [comment]
Thanks, I'll close this

**Pull request closed without merging**
