### PR TITLE
Implement code generation as a three-step process

### LINKED ISSUE #577: SwiftSyntaxBuilderGeneration Cannot Depend on SwiftSyntaxBuilder
This creates a chicken-and-egg problem when any aspect of the syntax nodes changes that also affects the builders. Consider the addition of a hypothetical node `FooSyntax`. When a user goes to update their checkouts and reruns the code generation script, they are greeted with a build failure. At first blush, this is because `ExpressibleByFooSyntax` is not regenerated by `build-script.py generate-source-code`. So the next thought would then be - just `swift run SwiftSyntaxBuilderGeneration` and regenerate the builder. But! that module no longer builds thanks to the prior source code generation script invocation.

Okay, so start over. Regenerate the builders, then regenerate syntax. Also doesn't work - the builder depends on the updated syntax nodes being present. But in order to do that... you have to run `build-script.py generate-source-code`.

Going forward, there cannot be a dependency between these two modules. We must be able to bootstrap SwiftSyntax when things change here.

### PR DESCRIPTION
**Pull request by ahoppen**
To make sure code generation works when adding new nodes, implement it as a three-stage process.

1. Re-generate the gyb files in SwiftSyntaxBuilderGeneration. This only re-generates the Swift files which essentially match the Python files in gyb_syntax_support. This does not generate any new syntax nodes etc.
2. Run code generation using SwiftSyntaxBuilder (i.e. run SwiftSyntaxBuilderGeneration). This still compiles because stage 1 did not modify any types in SwiftSyntax
3. Generate the remaining gyb files to match the files that were generated using SwiftSyntaxBuilderGeneration in step 2. Since this is Python, it will always pass.

Resolves #577

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by CodaFi — APPROVED** [review]
Approach LGTM. I was able to successfully use https://github.com/apple/swift/pull/60629 to test this.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
