### PR TITLE
Remove `@frozen` attributes

### PR DESCRIPTION
**Pull request by ahoppen**
These only existed to work around a miscompile in Swift 5.5. Since we no longer support it, we can remove the workaround.

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test macOS

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by ahoppen** [comment]
@swift-ci Please clean test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by kimdv** [comment]
@swift-ci please test linux

**Comment by kimdv** [comment]
@swift-ci please test windows

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
