### PR TITLE
Fix warnings when generating the docc documentation archive for SwiftSyntax

### PR DESCRIPTION
**Pull request by ahoppen**

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by bnbarham — APPROVED** [review]

**Review by kimdv — APPROVED** [review]

**Comment by kimdv** [comment]
@swift-ci please test Linux

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Comment by ahoppen** [comment]
@swift-ci Please test Linux

**Pull request merged**
