### PR TITLE
Update swift-syntax revision

### PR DESCRIPTION
**Pull request by kimdv**
- [x] Depends on #1113

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test linux

**Comment by kimdv** [comment]
@swift-ci plet test Linux

**Comment by kimdv** [comment]
@swift-ci please test Linux

**Review by ahoppen — APPROVED** [review]

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
Will wait until #1147 is merged

**Comment by stevapple** [comment]
> Will wait until #1147 is merged

Shall we get #1148 in too?

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test

**Pull request merged**
