### PR TITLE
Remove convenience initializers

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — COMMENTED** [review]
Thank you.

I just went through the convenience initializers as well and think the following changes would also make sense. If you’ve got time, I think it would be good to do them in this PR. But we can also merge this as-is and I’ll create a follow-up PR
- `FunctionParameterSyntax` should take a `PartialSyntaxNodeString` instead of a `String`
- I think `SwitchCaseSyntax` could also be represented as a convenience initializer in SyntaxNodeWithBody.swift
- Rename the `MARK: CustomAttribute` to `MARK: Attribute` and sort it to the top of the file to maintain alphabetical order

**Comment by kimdv** [comment]
Will add them to this PR

**Comment by kimdv** [comment]
@ahoppen should `TupleExprElementSyntax` I also replace the string with an `PartialSyntaxNodeString` and then change to `label: label.map { TokenSyntax("\($0)") }`

**Comment by kimdv** [comment]
Also removed the one from `IfStmtSyntax` as there is one in `SyntaxNodeWithBody.swift`

**Comment by kimdv** [comment]
Also removed `TernaryExprSyntax` as we can use `ExprSyntax` now

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
> @ahoppen should `TupleExprElementSyntax` I also replace the string with an `PartialSyntaxNodeString` and then change to `label: label.map { TokenSyntax("\($0)") }`

For `TupleExprElementSyntax` it’s fine since we aren’t parsing the string – we are using it as the contents of an identifier.

**Review by ahoppen — APPROVED** [review]
Thank you!

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test

**Pull request merged**
