### PR TITLE
Fix colon followed by right paren spacing

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — COMMENTED** [review]
I think what you want to do, is mark the colon in `DeclNameArgument` as not requiring a space so that we also don’t insert a space after `raw:` in `Foo.init(raw:otherParam:)`.

**Comment by kimdv** [comment]
Nice, thanks Alex!

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]
Great

**Pull request merged**
