### PR TITLE
Renamed generate-swiftsyntax to generate-swift-syntax

### PR DESCRIPTION
**Pull request by arirays**
Fixes issue #1935

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by arirays** [comment]
Hi, is it possible that I have a merge conflict due to renaming Sources file folder generate-swiftsyntax?

**Review by ahoppen — APPROVED** [review]
Looks good to me. Thanks for your first contribution to the swift-syntax project, @arirays.

I’ll run CI and if that passes, I’ll merge the PR.

**Comment by ahoppen** [comment]
Oh, actually, I just see that there are merge conflicts. @arirays could you rebase your changes on top of current main and then force push your updated branch?

**Comment by arirays** [comment]
Thank you @ahoppen ! 
I rebased my changes onto main.

**Comment by ahoppen** [comment]
It looks like there are still merge conflicts. Did you pull `main` before rebasing?

**Comment by arirays** [comment]
Yes I did.

**Comment by ahoppen** [comment]
Thanks. Let’s see what CI has to say.

@swift-ci Please test

**Comment by ahoppen** [comment]
I’m sorry that I forgot to check the CI results after I triggered it. Would you mind doing another rebase @arirays? 🙈

**Comment by arirays** [comment]
Yes, I'll do another rebase 😊

**Comment by kimdv** [comment]
@swift-ci please test

**Pull request closed without merging**
