### PR TITLE
Allow parsing for enum case element parameter on new line

### LINKED ISSUE #1709: Parsing fails if line break between enum case element name and parameter clause
### Issue Kind

Parse of Valid Source Failed

### Source Code

This errors out without good reason (with both the new and legacy parsers):
```swift
enum E {
  case a
    (Int)
}
```

Similarly formatted function/subscript parameter lists parse fine.

### Description

_No response_

### PR DESCRIPTION
**Pull request by kimdv**
Resolves #1709

### CODE REVIEW

**Comment by ahoppen** [comment]
CC @bnbarham @rintaro @DougGregor Any concerns with this PR? See https://github.com/apple/swift-syntax/issues/1709 for an explanation of the motivation.

**Comment by rintaro** [comment]
Since func/subscript parameter clause allows newlines before `(`, it's good to be consistent. Call arguments enforces `(` be on the same line, but that is mainly for disambiguation.
TBH I personally don't want to allow newlines before `(` even for `func`, but I couldn't find a strong reason to disallow them.

**Comment by DougGregor** [comment]
> Since func/subscript parameter clause allows newlines before `(`, it's good to be consistent.

This is the argument that wins me over. I agree with @rintaro that I'd prefer not to allow newlines before the `(` for any of func/decl/subscript/etc. However, since we already allow them, I'd rather be consistent and also allow them for cases. There's no chance for ambiguity here because there are no expressions within an enum scope.

**Comment by DougGregor** [comment]
@swift-ci please test

**Review by DougGregor — APPROVED** [review]
This can't

**Comment by ahoppen** [comment]
Thanks for your feedback @rintaro and @DougGregor. I agree with you as well, bug just wanted to double-check

**Review by ahoppen — APPROVED** [review]

**Pull request merged**
