### PR TITLE
Remove attribute kind gyb

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
Just for my understanding: Did you essentially just remove the `.gyb` files, move the `AttributeKind.swift` from `gyb_generated` to the top level and run swift-format on it?

**Review by ahoppen — APPROVED** [review]
Nice. One less `.gyb` file 🥳

**Comment by ahoppen** [comment]
Sounds good to me. I’m pretty sure we aren’t using these parameters anywhere so we should be able to just remove them, so I don’t really care either way.

**Comment by kimdv** [comment]
I've made them private. 
IMO I thinks it's better to have them, as it reduce the chances of typos that's hard to see when debugging

**Comment by kimdv** [comment]
> Sounds good to me. I’m pretty sure we aren’t using these parameters anywhere so we should be able to just remove them, so I don’t really care either way.

Or are we not using the `options` anywhere?

**Comment by ahoppen** [comment]
Nope, I don’t think so. These files are more or less 1:1 copies from the corresponding files in apple/swift and they are used in apple/swift.

**Comment by kimdv** [comment]
Will merge now. 

I can look into them after this PR

**Pull request merged**
