### PR TITLE
Add declaration-level `consuming` and `borrowing` modifiers from SE-0377

### PR DESCRIPTION
**Pull request by jckarter**
swift-syntax parser updates for https://github.com/apple/swift/pull/63990

### CODE REVIEW

**Comment by jckarter** [comment]
https://github.com/apple/swift/pull/63990

@swift-ci Please test

**Review by ahoppen — APPROVED** [review]

**Comment by jckarter** [comment]
https://github.com/apple/swift/pull/63990

@swift-ci Please test

**Comment by jckarter** [comment]
https://github.com/apple/swift/pull/63990

@swift-ci Please test

**Comment by jckarter** [comment]
https://github.com/apple/swift/pull/63990

@swift-ci Please test

**Comment by jckarter** [comment]
@swift-ci Please test

**Pull request merged**
