### PR TITLE
Introduce a source accurate and structural view of a SwiftSyntax tree

### PR DESCRIPTION
**Pull request by ahoppen**
`SyntaxTreeViewMode` allows two different views on a SwiftSyntax tree:

1. Either a purely `sourceAccurate` view, which skips over all missing children but traverses garbage syntax (once implemented). This mode is intended for clients that operate at the source code level, like swift-format
2. For clients that don’t care about 100% about source fidelity but would like to view the syntax tree for structural analysis with fixes from the parser applied, there’s the `fixedUp` view. This includes missing nodes (because the user probably meant to write these) and skips over garbage nodes (because the client will likely have a hard time reasoning about these nodes if the parser couldn’t make sense of them)

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-stress-tester/pull/181

@swift-ci Please test

**Review by bnbarham — COMMENTED** [review]
I think it'd be nice if we kept the original API as well and just had it default to `.sourceAccurate`. Fewer changes in all the clients that way. But I like the additions in general - I had done the `NonNilRawSyntaxChildren` in my own changes 😅.

**Comment by ahoppen** [comment]
I made two changes to the PR:
- Renamed the parameters from `syntaxTreeViewMode` to `viewMode` (if you’ve got better ideas for naming, I’m open to suggestions)
- Added the `firstToken` etc. getters on `Syntax` again. These default to the source accurate view.

**Comment by ahoppen** [comment]
https://github.com/apple/swift-stress-tester/pull/181

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-stress-tester/pull/181

@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-stress-tester/pull/181

@swift-ci Please test

**Comment by fwcd** [comment]
I think this PR accidentally reverted the rename from `Examples` to `Snippets` in #477.

**Pull request merged**
