### PR TITLE
Make swift-syntax (mostly) build in Swift 6 mode

### PR DESCRIPTION
**Pull request by ahoppen**
This almost makes swift-syntax build in Swift 6 mode. The only change holding us back is that `CommandLine.arguments` is a static variable and accessing it in Swift 6 mode raises an error (rdar://113799564).

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]
Can't say I'm a huge fan of the import condition, but I also have no better solution.

**Pull request merged**
