### PR TITLE
Rename `SwiftSyntaxBuilderGeneration` to `generate-swift-syntax-builder`

### PR DESCRIPTION
**Pull request by fwcd**
As suggested in https://github.com/apple/swift-syntax/pull/580#issuecomment-1213174062. This follows the convention that executable targets are named in kebab-case (e.g. like this repo's `lit-test-helper`, SourceKit-LSP's `sourcekit-lsp`, SwiftFormat's `swift-format`, ...).

### CODE REVIEW

**Comment by fwcd** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
Actually, now that I read the name, what do you think about making it more descriptive and name it `generate-swift-syntax-builder`?

**Comment by fwcd** [comment]
Done!

@swift-ci please test

**Comment by fwcd** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Pull request merged**
