### PR TITLE
Add syntax node for PackExpansionTypeRepr

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
Could you also add support for parsing `PackExpansionTypeRepr` in the new parser that lives in this repo?

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@swift-ci Please test

**Pull request merged**
