### PR TITLE
Fix leading newline in source file syntax

### PR DESCRIPTION
**Pull request by kimdv**
Will fix https://github.com/apple/swift-syntax/pull/1343#discussion_r1105949830

### CODE REVIEW

**Comment by ahoppen** [comment]
Did you run CodeGeneration after this change? I don’t see the leading newlines before the copyright headers disappear.

**Comment by kimdv** [comment]
> Did you run CodeGeneration after this change? I don’t see the leading newlines before the copyright headers disappear.

WE need to merge this before we can update swift-syntax in CodeGeneration

**Review by ahoppen — APPROVED** [review]
Thank you

**Comment by ahoppen** [comment]
@swift-ci Please test

**Pull request merged**
