### PR TITLE
Add diagnostic message for identifier editor placeholder

### PR DESCRIPTION
**Pull request by kimdv**
Part of fixing an TODOs in here: https://github.com/apple/swift-syntax/issues/1373

I just wanna ask if I'm on the right path.

### CODE REVIEW

**Review by ahoppen — COMMENTED** [review]
This won’t work as-is because there are other places that also consume an identifier and would consume the editor placeholder as a normal identifier without emitting an error.

Instead, I think the error should be emitted by the Lever. You can take a look at Cursor.swift. There are a few cases that add a `LexerDiagnostic`. We should do the same for editor placeholders.

**Review by ahoppen — APPROVED** [review]
That’s exactly what I was thinking of 🤩

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by kimdv** [comment]
@swift-ci please test macOS

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Review by ahoppen — APPROVED** [review]

**Comment by kimdv** [comment]
https://github.com/apple/swift/pull/64382

@swift-ci please test

**Pull request merged**
