### PR TITLE
Add _BridgeObject and _TrivialStride layouts

### PR DESCRIPTION
**Pull request by drexin**
Both layout kinds are useful for pre-specializations of commonly emitted generic function specializations.

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Review by ahoppen — COMMENTED** [review]
Could you add test cases for these layouts?

**Comment by drexin** [comment]
> Could you add test cases for these layouts?

Absolutely!

**Comment by drexin** [comment]
@swift-ci test

**Review by ahoppen — APPROVED** [review]

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test windows

**Pull request merged**
